[PIN-2958] Listing attributi su attributes-registry-process
pagopa/interop-be-attribute-registry-process pull request #3
Opened 2023-03-29 13:13 UTC by bloodsky

2023-03-30 07:16 UTC, AsterITA commented on src/main/scala/it/pagopa/interop/attributeregistryprocess/api/impl/AttributeRegistryApiServiceImpl.scala
> +  def getAll[T](limit: Int)(get: (Int, Int) => Future[Seq[T]]): Future[Seq[T]] = {
```suggestion
  private def getAll[T](limit: Int)(get: (Int, Int) => Future[Seq[T]]): Future[Seq[T]] = {
```

2023-03-30 09:28 UTC, galales requested changes

2023-03-30 09:28 UTC, galales commented on src/main/resources/interface-specification.yml
> +      summary: Get attributes from Read Model
```suggestion
      summary: Get attributes
```

2023-03-30 09:28 UTC, galales commented on src/main/resources/interface-specification.yml
> +      description: 'returns attributes of kinds from the Read Model.'
```suggestion
      description: 'returns attributes'
```

2023-03-30 09:28 UTC, galales commented on src/main/resources/interface-specification.yml
> +          required: true
`limit` and `offset` require boundaries.
You can see other processes for reference

2023-03-30 09:28 UTC, galales commented on src/main/resources/interface-specification.yml
>          - attributes
for convention this field should be named `results`

2023-03-30 09:28 UTC, galales commented on src/main/resources/interface-specification.yml
> +              type: string
```suggestion
              $ref: '#/components/schemas/AttributeKind'
```

2023-03-30 09:28 UTC, galales commented on src/main/scala/it/pagopa/interop/attributeregistryprocess/common/readmodel/ReadModelQueries.scala
> +    val query = mapToVarArgs(kinds.map(Filters.eq("kind", _)))(Filters.or).getOrElse(Filters.empty())
filter by attribute name is missing

2023-03-30 09:28 UTC, galales commented on src/main/scala/it/pagopa/interop/attributeregistryprocess/api/impl/package.scala
> +  implicit def attributeManagementFormat: RootJsonFormat[AttributeManagement] = jsonFormat7(AttributeManagement)
These should not be required
```suggestion
```

2023-03-30 09:28 UTC, galales commented on src/main/scala/it/pagopa/interop/attributeregistryprocess/common/readmodel/ReadModelQueries.scala
> +  )(implicit ec: ExecutionContext): Future[PaginatedResult[Attribute]] = {
The stored model is the Persistent, not the Api
```suggestion
  )(implicit ec: ExecutionContext): Future[PaginatedResult[PersistentAttribute]] = {
```
You can import its codecs from `it.pagopa.interop.attributeregistrymanagement.model.persistence.JsonFormats._`

2023-03-30 09:28 UTC, galales commented on src/main/resources/interface-specification.yml
> +      parameters:
missing `name` filter

2023-03-30 09:40 UTC, bloodsky commented on src/main/scala/it/pagopa/interop/attributeregistryprocess/common/readmodel/ReadModelQueries.scala
> +    val query = mapToVarArgs(kinds.map(Filters.eq("kind", _)))(Filters.or).getOrElse(Filters.empty())
Should we add the name parameter in the [specifications](https://pagopa.atlassian.net/browse/PIN-2958)?

2023-03-30 15:55 UTC, TonioGela approved these changes

2023-04-03 07:46 UTC, galales approved these changes

2023-04-03 08:15 UTC, merged